build:
  version: "2.0"

accounts:
  message: "Hello from Accounts QA Service"
  contactDetails:
    name: "wanwa QA"
    email: "qualitiesassurance@example.com"
  onCallSupport:
    - (090) 1234-3379
    - (090) 8765-0000